# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wk_8uarA1XlNAWiaQS8InV9PBeI9CXkD

MNIST is a supervised Classification. COnverting it to unsupervised with t-SNE
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import datasets
from sklearn import manifold

# %matplotlib inline

data =datasets.fetch_openml('mnist_784',version=1,return_X_y=True)
pixelVals, targets=data
targets=targets.astype(int)

single_img=pixelVals[1,:].reshape(28,28);
plt.imshow(single_img, cmap="gray")

tsne=manifold.TSNE(n_components=2, random_state=42)
transformed_data=tsne.fit_transform(pixelVals[:3000,:])

tsne_df=pd.DataFrame(np.column_stack((transformed_data,targets[:3000])),columns=["X","Y","Targets"])
tsne_df.loc[:,"Targets"]=tsne_df.Targets.astype(int)

tsne_df.head()

grid=sns.FacetGrid(tsne_df,hue="Targets",size=8);
grid.map(plt.scatter,"X","Y").add_legend()